# Generated by Django 5.0.6 on 2024-06-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('TRP', 'TRP'), ('C50', 'C50')], default='TRP', max_length=20),
        ),
    ]
