# Generated by Django 5.0.6 on 2024-06-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('TRP', 'TRP'), ('C50', 'C50'), ('APOLLO', 'APOLLO'), ('G-STREET', 'G-STREET'), ('MINI-JET', 'MINI-JET'), ('CITY', 'CITY'), ('CRUZER', 'CRUZER'), ('ALPHA', 'ALPHA')], default='TRP', max_length=20),
        ),
    ]
