# Generated by Django 5.0.6 on 2024-07-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='darija_name',
            field=models.CharField(default='darija', max_length=100),
        ),
    ]
