# Generated by Django 5.0.6 on 2024-07-01 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_darija_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='darija_name',
        ),
    ]
